### ISSUE TITLE
Port should be configurable via bash

### ISSUE THREAD

**Issue by TimPietrusky** [NERDDISCO/VisionLord#3]
The port in [main.go](https://github.com/NERDDISCO/VisionLord/blob/master/server/main.go) is hard coded to `1337`, but it should be configurable trough the bash via a `-port` cmd argument.

**Comment by kevingimbel** [comment]
@TimPietrusky done. https://github.com/NERDDISCO/VisionLord/pull/31

**Comment by TimPietrusky** [comment]
@kevingimbel Thank you super much! Added you to the list of contributors <3
